package com.song.db.mapper;

import com.song.db.domain.GraduPermission;
import com.song.db.domain.GraduPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GraduPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_permission
     *
     * @mbg.generated
     */
    long countByExample(GraduPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_permission
     *
     * @mbg.generated
     */
    int deleteByExample(GraduPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_permission
     *
     * @mbg.generated
     */
    int insert(GraduPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_permission
     *
     * @mbg.generated
     */
    int insertSelective(GraduPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_permission
     *
     * @mbg.generated
     */
    GraduPermission selectOneByExample(GraduPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_permission
     *
     * @mbg.generated
     */
    GraduPermission selectOneByExampleSelective(@Param("example") GraduPermissionExample example, @Param("selective") GraduPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_permission
     *
     * @mbg.generated
     */
    List<GraduPermission> selectByExampleSelective(@Param("example") GraduPermissionExample example, @Param("selective") GraduPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_permission
     *
     * @mbg.generated
     */
    List<GraduPermission> selectByExample(GraduPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_permission
     *
     * @mbg.generated
     */
    GraduPermission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") GraduPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_permission
     *
     * @mbg.generated
     */
    GraduPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_permission
     *
     * @mbg.generated
     */
    GraduPermission selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GraduPermission record, @Param("example") GraduPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GraduPermission record, @Param("example") GraduPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GraduPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GraduPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GraduPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}