package com.song.db.mapper;

import com.song.db.domain.GraduNoticeAdmin;
import com.song.db.domain.GraduNoticeAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GraduNoticeAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice_admin
     *
     * @mbg.generated
     */
    long countByExample(GraduNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice_admin
     *
     * @mbg.generated
     */
    int deleteByExample(GraduNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice_admin
     *
     * @mbg.generated
     */
    int insert(GraduNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice_admin
     *
     * @mbg.generated
     */
    int insertSelective(GraduNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice_admin
     *
     * @mbg.generated
     */
    GraduNoticeAdmin selectOneByExample(GraduNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice_admin
     *
     * @mbg.generated
     */
    GraduNoticeAdmin selectOneByExampleSelective(@Param("example") GraduNoticeAdminExample example, @Param("selective") GraduNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice_admin
     *
     * @mbg.generated
     */
    List<GraduNoticeAdmin> selectByExampleSelective(@Param("example") GraduNoticeAdminExample example, @Param("selective") GraduNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice_admin
     *
     * @mbg.generated
     */
    List<GraduNoticeAdmin> selectByExample(GraduNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice_admin
     *
     * @mbg.generated
     */
    GraduNoticeAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") GraduNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice_admin
     *
     * @mbg.generated
     */
    GraduNoticeAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice_admin
     *
     * @mbg.generated
     */
    GraduNoticeAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GraduNoticeAdmin record, @Param("example") GraduNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GraduNoticeAdmin record, @Param("example") GraduNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GraduNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GraduNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GraduNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}