package com.song.db.mapper;

import com.song.db.domain.GraduRole;
import com.song.db.domain.GraduRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GraduRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_role
     *
     * @mbg.generated
     */
    long countByExample(GraduRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_role
     *
     * @mbg.generated
     */
    int deleteByExample(GraduRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_role
     *
     * @mbg.generated
     */
    int insert(GraduRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_role
     *
     * @mbg.generated
     */
    int insertSelective(GraduRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_role
     *
     * @mbg.generated
     */
    GraduRole selectOneByExample(GraduRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_role
     *
     * @mbg.generated
     */
    GraduRole selectOneByExampleSelective(@Param("example") GraduRoleExample example, @Param("selective") GraduRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_role
     *
     * @mbg.generated
     */
    List<GraduRole> selectByExampleSelective(@Param("example") GraduRoleExample example, @Param("selective") GraduRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_role
     *
     * @mbg.generated
     */
    List<GraduRole> selectByExample(GraduRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_role
     *
     * @mbg.generated
     */
    GraduRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") GraduRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_role
     *
     * @mbg.generated
     */
    GraduRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_role
     *
     * @mbg.generated
     */
    GraduRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GraduRole record, @Param("example") GraduRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GraduRole record, @Param("example") GraduRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GraduRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GraduRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GraduRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}