package com.song.db.mapper;

import com.song.db.domain.GraduNotice;
import com.song.db.domain.GraduNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GraduNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice
     *
     * @mbg.generated
     */
    long countByExample(GraduNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice
     *
     * @mbg.generated
     */
    int deleteByExample(GraduNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice
     *
     * @mbg.generated
     */
    int insert(GraduNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice
     *
     * @mbg.generated
     */
    int insertSelective(GraduNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice
     *
     * @mbg.generated
     */
    GraduNotice selectOneByExample(GraduNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice
     *
     * @mbg.generated
     */
    GraduNotice selectOneByExampleSelective(@Param("example") GraduNoticeExample example, @Param("selective") GraduNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice
     *
     * @mbg.generated
     */
    List<GraduNotice> selectByExampleSelective(@Param("example") GraduNoticeExample example, @Param("selective") GraduNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice
     *
     * @mbg.generated
     */
    List<GraduNotice> selectByExample(GraduNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice
     *
     * @mbg.generated
     */
    GraduNotice selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") GraduNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice
     *
     * @mbg.generated
     */
    GraduNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice
     *
     * @mbg.generated
     */
    GraduNotice selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GraduNotice record, @Param("example") GraduNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GraduNotice record, @Param("example") GraduNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GraduNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GraduNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GraduNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}