package com.song.db.mapper;

import com.song.db.domain.GraduFootprint;
import com.song.db.domain.GraduFootprintExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GraduFootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_footprint
     *
     * @mbg.generated
     */
    long countByExample(GraduFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_footprint
     *
     * @mbg.generated
     */
    int deleteByExample(GraduFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_footprint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_footprint
     *
     * @mbg.generated
     */
    int insert(GraduFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_footprint
     *
     * @mbg.generated
     */
    int insertSelective(GraduFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_footprint
     *
     * @mbg.generated
     */
    GraduFootprint selectOneByExample(GraduFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_footprint
     *
     * @mbg.generated
     */
    GraduFootprint selectOneByExampleSelective(@Param("example") GraduFootprintExample example, @Param("selective") GraduFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_footprint
     *
     * @mbg.generated
     */
    List<GraduFootprint> selectByExampleSelective(@Param("example") GraduFootprintExample example, @Param("selective") GraduFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_footprint
     *
     * @mbg.generated
     */
    List<GraduFootprint> selectByExample(GraduFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_footprint
     *
     * @mbg.generated
     */
    GraduFootprint selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") GraduFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_footprint
     *
     * @mbg.generated
     */
    GraduFootprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_footprint
     *
     * @mbg.generated
     */
    GraduFootprint selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_footprint
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GraduFootprint record, @Param("example") GraduFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_footprint
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GraduFootprint record, @Param("example") GraduFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GraduFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GraduFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GraduFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_footprint
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}