package com.song.db.mapper;

import com.song.db.domain.GraduUser;
import com.song.db.domain.GraduUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GraduUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_user
     *
     * @mbg.generated
     */
    long countByExample(GraduUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_user
     *
     * @mbg.generated
     */
    int deleteByExample(GraduUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_user
     *
     * @mbg.generated
     */
    int insert(GraduUser record);

//    List<GraduUser> insertByExcel(GraduUserExample example);
    int insertByExcel(List<GraduUser> user);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_user
     *
     * @mbg.generated
     */
    int insertSelective(GraduUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_user
     *
     * @mbg.generated
     */
    GraduUser selectOneByExample(GraduUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_user
     *
     * @mbg.generated
     */
    GraduUser selectOneByExampleSelective(@Param("example") GraduUserExample example, @Param("selective") GraduUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_user
     *
     * @mbg.generated
     */
    List<GraduUser> selectByExampleSelective(@Param("example") GraduUserExample example, @Param("selective") GraduUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_user
     *
     * @mbg.generated
     */
    List<GraduUser> selectByExample(GraduUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_user
     *
     * @mbg.generated
     */
    GraduUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") GraduUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_user
     *
     * @mbg.generated
     */
    GraduUser selectByPrimaryKey(Integer id);


//    GraduUser selectByNickname(String nickname);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_user
     *
     * @mbg.generated
     */
    GraduUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GraduUser record, @Param("example") GraduUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GraduUser record, @Param("example") GraduUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GraduUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GraduUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_user
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GraduUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_user
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}