package com.song.db.mapper;

import com.song.db.domain.GraduLog;
import com.song.db.domain.GraduLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GraduLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_log
     *
     * @mbg.generated
     */
    long countByExample(GraduLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_log
     *
     * @mbg.generated
     */
    int deleteByExample(GraduLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_log
     *
     * @mbg.generated
     */
    int insert(GraduLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_log
     *
     * @mbg.generated
     */
    int insertSelective(GraduLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_log
     *
     * @mbg.generated
     */
    GraduLog selectOneByExample(GraduLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_log
     *
     * @mbg.generated
     */
    GraduLog selectOneByExampleSelective(@Param("example") GraduLogExample example, @Param("selective") GraduLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_log
     *
     * @mbg.generated
     */
    List<GraduLog> selectByExampleSelective(@Param("example") GraduLogExample example, @Param("selective") GraduLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_log
     *
     * @mbg.generated
     */
    List<GraduLog> selectByExample(GraduLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_log
     *
     * @mbg.generated
     */
    GraduLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") GraduLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_log
     *
     * @mbg.generated
     */
    GraduLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_log
     *
     * @mbg.generated
     */
    GraduLog selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GraduLog record, @Param("example") GraduLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GraduLog record, @Param("example") GraduLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GraduLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GraduLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_log
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GraduLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_log
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}