package com.song.db.mapper;

import com.song.db.domain.GraduKeyword;
import com.song.db.domain.GraduKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GraduKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_keyword
     *
     * @mbg.generated
     */
    long countByExample(GraduKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_keyword
     *
     * @mbg.generated
     */
    int deleteByExample(GraduKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_keyword
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_keyword
     *
     * @mbg.generated
     */
    int insert(GraduKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_keyword
     *
     * @mbg.generated
     */
    int insertSelective(GraduKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_keyword
     *
     * @mbg.generated
     */
    GraduKeyword selectOneByExample(GraduKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_keyword
     *
     * @mbg.generated
     */
    GraduKeyword selectOneByExampleSelective(@Param("example") GraduKeywordExample example, @Param("selective") GraduKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_keyword
     *
     * @mbg.generated
     */
    List<GraduKeyword> selectByExampleSelective(@Param("example") GraduKeywordExample example, @Param("selective") GraduKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_keyword
     *
     * @mbg.generated
     */
    List<GraduKeyword> selectByExample(GraduKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_keyword
     *
     * @mbg.generated
     */
    GraduKeyword selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") GraduKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_keyword
     *
     * @mbg.generated
     */
    GraduKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_keyword
     *
     * @mbg.generated
     */
    GraduKeyword selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_keyword
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GraduKeyword record, @Param("example") GraduKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_keyword
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GraduKeyword record, @Param("example") GraduKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GraduKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GraduKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GraduKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_keyword
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}