package com.song.db.mapper;

import com.song.db.domain.GraduStorage;
import com.song.db.domain.GraduStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GraduStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_storage
     *
     * @mbg.generated
     */
    long countByExample(GraduStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_storage
     *
     * @mbg.generated
     */
    int deleteByExample(GraduStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_storage
     *
     * @mbg.generated
     */
    int insert(GraduStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_storage
     *
     * @mbg.generated
     */
    int insertSelective(GraduStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_storage
     *
     * @mbg.generated
     */
    GraduStorage selectOneByExample(GraduStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_storage
     *
     * @mbg.generated
     */
    GraduStorage selectOneByExampleSelective(@Param("example") GraduStorageExample example, @Param("selective") GraduStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_storage
     *
     * @mbg.generated
     */
    List<GraduStorage> selectByExampleSelective(@Param("example") GraduStorageExample example, @Param("selective") GraduStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_storage
     *
     * @mbg.generated
     */
    List<GraduStorage> selectByExample(GraduStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_storage
     *
     * @mbg.generated
     */
    GraduStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") GraduStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_storage
     *
     * @mbg.generated
     */
    GraduStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_storage
     *
     * @mbg.generated
     */
    GraduStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GraduStorage record, @Param("example") GraduStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GraduStorage record, @Param("example") GraduStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GraduStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GraduStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GraduStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gradu_storage
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}